const { GoogleGenerativeAI } = require('@google/generative-ai');

const apiKey = process.env.REACT_APP_GEMINI_API_KEY;
const genAI = new GoogleGenerativeAI(apiKey);

const model = genAI.getGenerativeModel({
  model: 'gemini-1.5-flash',
});

const generationConfig = {
  temperature: 1,
  topP: 0.95,
  topK: 64,
  maxOutputTokens: 8192,
  responseMimeType: 'application/json',
};

async function summarizeAndExtractPrescription(transcription) {
  try {
    const parts = [
      {text: "input: Miss Williams. How are you feeling today? Good afternoon doctor. I am not feeling too well unfortunately I have been having this terrible cough for the past weeks and I feel so congested making it hard to sleep at night and my throat feels really sore. I am sorry to hear that. Have you noticed any other symptoms like fever, headache or difficulty in breathing? Yes, I have a slightly fever off and on and my head feels heavy but no difficulty breathing. It mostly the conjectures and the constant cough that are bothering me. That sounds like a respiratory infection. It possibly viral but with the fever and congestion there may be a bacterial component as well. I am going to prescribe a combination of medication to help manage your symptoms and address the infection. Ok doctor, what medication will I need? First I am prescribing moxilin which is an antibiotic. This will help clear up any bacterial infection that may be causing the congestion and cough. The dosage is 500 milligrams and you will take it three times a day for seven days. Make sure to take it with food to avoid stomach upset. Got it. I'll take it with meals. What way should I take next? I am prescribing guafnicin which is an expectorant. It will help loosen the mucus in your chest making it easier to cough up and clear your airways. Take 200 milligrams every 4 hours as needed but not more than six doses in 24 hours. Make sure to drink plenty of water while taking guarantee as it works better when you are well hydrated. That sounds helpful. I have been having such trouble scuffing up the mucus. I am also going to give you leupron for the fever and pain you might be experiencing, particularly the headaches and sore throat. You can take 400 milligrams every 6 hours but make sure you take it after meals to avoid irritating your stomach. Okay, so I will take the euphrophen when needed to. Anything else? Yes. Lastly, I will prescribe diphenhydramine. It's an anesthetamine that will help reduce our congestion and help you sleep at night since it can cause drowsiness. Take 25 milligrams at night before bed. Thanks for explaining everything doctor. So just to clarify. Thank you doctor. I will follow the instructions and let you know if there's no improvement. You're welcome. I hope you feel better soon. Miss Williams. Take care of."},
    {text: "output: {\n  \"summary\": \"In this medical conversation, Miss Williams consults her doctor about a persistent cough, congestion, difficulty sleeping, and a sore throat that has lasted for weeks. She also reports having occasional fever and a heavy feeling in her head, though she has no breathing difficulties.The doctor suspects a respiratory infection, possibly viral but with a bacterial component due to the fever and congestion. The doctor prescribes a combination of medications:Amoxicillin (antibiotic): 500 mg, three times daily for seven days, taken with food to avoid stomach upset.Guaifenesin (expectorant): 200 mg every four hours as needed (maximum six doses in 24 hours), to help loosen mucus. Adequate hydration is recommended.Ibuprofen: 400 mg every six hours for fever and pain relief, taken after meals to avoid stomach irritation.Diphenhydramine (antihistamine): 25 mg at night to reduce congestion and help with sleep.Miss Williams agrees to follow the prescribed treatment and informs the doctor she will reach out if her symptoms do not improve.\n\",\n  \"medicines\": [\n    {\n      \"name\": \"Amoxicillin\",\n      \"dosage\": \"500 mg\",\n      \"usage_instructions\": \"Take three times a day for seven days with food to avoid stomach upset.\",\n      \"purpose\": \"Antibiotic to treat potential bacterial infection.\"\n    },\n    {\n      \"name\": \"Guaifenesin\",\n      \"dosage\": \"200 mg\",\n      \"usage_instructions\": \"Take every 4 hours as needed, but not more than six doses in 24 hours. Drink plenty of water to stay hydrated.\",\n      \"purpose\": \"Expectorant to loosen mucus and clear the airways.\"\n    },\n    {\n      \"name\": \"Ibuprofen\",\n      \"dosage\": \"400 mg\",\n      \"usage_instructions\": \"Take every six hours as needed after meals to avoid stomach irritation.\",\n      \"purpose\": \"Pain reliever and fever reducer.\"\n    },\n    {\n      \"name\": \"Diphenhydramine\",\n      \"dosage\": \"25 mg\",\n      \"usage_instructions\": \"Take at night before bed.\",\n      \"purpose\": \"Antihistamine to reduce congestion and help with sleep.\"\n    }\n  ]\n}"},
    {text: "input: Good morning. Please have a seat here. Whats the problem? I have a terrible stomach ache. Do you have diarrhea? Yes, I do. Do you have any other symptoms? Yes, I feel sick. You mean you feel nauseous? Thats right. I feel like vomiting. And right now I feel dizzy too. When did the symptoms start? This morning. Yesterday evening. I ate something raw. Alright. Please take off your clothes to the waist and lie down there. Just tell me if it hurts when I do this. It doesn't hurt. Ouch. It hurts there. Okay. Let's hope it's just indigestion. But we'll need to run some diagnostic tests to be sure. We'll run a blood test, and we'll also need a urine sample. Can you give me something for the time being? Yes, I'll give you a prescription for indigestion tablets."},
    {text: "output: ```json\n{\n  \"summary\": \"The patient is experiencing a stomach ache, diarrhea, nausea, vomiting, and dizziness. Symptoms started yesterday evening after eating something raw. The doctor examined the patient and suspects indigestion. They prescribed indigestion tablets and ordered blood and urine tests for further diagnosis.\",\n  \"medicines\": [\n    {\n      \"name\": \"Indigestion tablets\",\n      \"dosage\": \"N/A\",\n      \"usage_instructions\": \"N/A\",\n      \"purpose\": \"To alleviate indigestion symptoms.\"\n    }\n  ]\n}\n```"},
    {text: "input: Doctor: Good morning, Mr. Johnson. How are you feeling today?Mr. Johnson: Good morning, doctor. I’m not feeling great. I’ve been having this sharp pain in my lower back for the past few days. It’s getting hard to move around, and sometimes it shoots down into my right leg.Doctor: I’m sorry to hear that. When did this pain start, and have you done anything that might have triggered it?Mr. Johnson: It started about four days ago, and I can’t think of anything specific. I didn’t lift anything heavy or have any accidents. It just started hurting out of nowhere.Doctor: Any other symptoms? Like numbness, tingling in your leg, or difficulty controlling your bladder or bowels?Mr. Johnson: Yes, actually. There’s been some tingling in my leg, especially when I sit for too long. No issues with bladder or bowels though.Doctor: It sounds like you may have a pinched nerve, possibly sciatica. It could be due to a herniated disc pressing on the nerve in your lower back. I’ll prescribe some medication to help with the pain and inflammation. In the meantime, we’ll schedule an MRI to get a better look at what’s going on.Mr. Johnson: That makes sense. What medications will I need?Doctor: First, I’ll prescribe naproxen, an anti-inflammatory drug, to reduce the swelling and pain. Take 500 mg twice a day after meals. I’ll also prescribe cyclobenzaprine, a muscle relaxant, 5 mg three times a day to help with any muscle spasms. Lastly, I’ll give you gabapentin to help manage the nerve pain. Start with 300 mg once at night and increase to twice a day if needed.Mr. Johnson: Okay, so naproxen for inflammation, cyclobenzaprine for muscle spasms, and gabapentin for nerve pain. Got it.Doctor: Exactly. Make sure to avoid any heavy lifting or strenuous activity for now. We’ll see how you respond to the medication, and I’ll follow up with you after we get the MRI results.Mr. Johnson: Thank you, doctor. I’ll follow the plan and take it easy.Doctor: You’re welcome, Mr. Johnson. I hope the medications help ease your pain. Take care."},
    {text: "output: ```json\n{\n  \"summary\": \"Mr. Johnson visits the doctor complaining about sharp lower back pain radiating down his right leg, starting four days ago. He also experiences tingling in his leg, particularly after prolonged sitting. The doctor suspects a pinched nerve, potentially sciatica, caused by a herniated disc. To manage the symptoms, the doctor prescribes:\\n\\n* Naproxen (anti-inflammatory): 500 mg twice a day after meals for pain and swelling.\\n* Cyclobenzaprine (muscle relaxant): 5 mg three times a day for muscle spasms.\\n* Gabapentin (nerve pain medication): 300 mg once at night, increasing to twice a day if needed. \\n\\nMr. Johnson is advised to avoid heavy lifting and strenuous activity. An MRI is scheduled to further assess the situation, and the doctor will follow up after receiving the results.\",\n  \"medicines\": [\n    {\n      \"name\": \"Naproxen\",\n      \"dosage\": \"500 mg\",\n      \"usage_instructions\": \"Take twice a day after meals.\",\n      \"purpose\": \"Anti-inflammatory to reduce swelling and pain.\"\n    },\n    {\n      \"name\": \"Cyclobenzaprine\",\n      \"dosage\": \"5 mg\",\n      \"usage_instructions\": \"Take three times a day.\",\n      \"purpose\": \"Muscle relaxant to relieve muscle spasms.\"\n    },\n    {\n      \"name\": \"Gabapentin\",\n      \"dosage\": \"300 mg\",\n      \"usage_instructions\": \"Take once at night, increase to twice a day if needed.\",\n      \"purpose\": \"Nerve pain medication to manage nerve pain.\"\n    }\n  ]\n}\n```"},
    {text: "input: Doctor: Good morning Mr. Sanchez. What brought you here today?Patient: Good morning doctor. My left shoulder hurts.Doctor: Oh, I’m sorry to hear that. When did it start?Patient: I can’t remember when it started doctor.Doctor: Are there any events that you think triggered your shoulder pain?Patient: I couldn’t think of anything doctor.Doctor: Oh I see. Is it painful all the time?Patient: It comes and goes doctor.Doctor: Has it been worsening?Patient: Yes, it has worsened now.Doctor: What is the pain like? Sharp? Dull? Tingling?Patient: It’s sharp doctor.Doctor: Does it radiate to any other parts of your body?Patient: Yes doctor, the pain radiates to my neck and arm at the same side.Doctor: On a scale of 1 to 10, with 10 as the highest and 0 as no pain at all, how severe is the pain?Patient: 8, doctor.Doctor: Oh it must be really painful for you. Is there anything that makes the pain worse?Patient: There’s nothing that I know of that makes the pain worse.Doctor: How about anything that makes it better? Like medications?Patient: It doesn’t improve with the medication I’m taking, but the pain lessens when I’m resting my shoulder.Doctor: What medication are you taking?Patient: Pain killer, doctor, Ibuprofen.Doctor: Have you ever had the same pain before?Patient: No, doctor.Doctor: Do you have any other symptoms?Patient: None, doctor.Doctor: Do you have any other medical problems like high blood pressure or diabetes?Patient: Yes, I have hypertensionDoctor: What medications are you taking for it?Patient: HCTZ, doctor.Doctor: Is there anybody in your family having heart problems, strokes or diabetes?Patient: My father died because of diabetes.Doctor: Ok. Now I’m going to ask you some personal questions that would be helpful. Do you mind?Patient: Not at all, doctor. Please feel free to ask questions.Doctor: Thanks. What type of work do you do?Patient: I’m a factory worker.Doctor: Okay. Do you drink?Patient: Yes, doctor, every Saturday night.Doctor: How many bottles do you drink?Patient: 4-5 bottles of beer per night doctor.Doctor: Okay, it’s better if you cut down on your drinking habits like you drink 2-3 bottles of beer only.Patient: I’ll try to do that, doctor, thanks!Doctor: Do you smoke?Patient: No, doctor.Doctor: Oh, that’s good. Thank you for answering all my questions. Now, you will go through some tests forme to have a clear diagnosis of your illness. Is this OK with you?"},
    {text: "output: ```json\n{\n  \"summary\": \"Mr. Sanchez visits the doctor complaining of sharp left shoulder pain radiating to his neck and arm. The pain comes and goes, has been worsening, and is rated 8/10 on the pain scale. He reports the pain is not aggravated by any specific activity but lessens with rest.  He's currently taking ibuprofen for pain but it's not providing significant relief. Mr. Sanchez has a history of hypertension and takes HCTZ for it. His father died due to diabetes. He works as a factory worker, drinks 4-5 bottles of beer every Saturday night, and is a non-smoker. The doctor advises Mr. Sanchez to reduce his alcohol consumption and orders further tests for a clear diagnosis.\",\n  \"medicines\": [\n    {\n      \"name\": \"Ibuprofen\",\n      \"dosage\": \"N/A\",\n      \"usage_instructions\": \"N/A\",\n      \"purpose\": \"Pain relief\"\n    },\n    {\n      \"name\": \"HCTZ\",\n      \"dosage\": \"N/A\",\n      \"usage_instructions\": \"N/A\",\n      \"purpose\": \"Treatment for hypertension\"\n    }\n  ]\n}\n```"},
    {text: "input: Patient – Good afternoon, Doctor.Doctor – Good afternoon, Mr. Bose. How are you?Patient – I’m doing good, doctor, but my daughter isn’t doing well. Everywhere, people are getting affected with COVID and I am really worried about her.Doctor – Please have a seat and tell me what happened.Patient – Last week, my daughter came back from Pune as her college was closed on account of COVID. From the second day, she has had high fever and has been coughing badly. I think that she has contracted the virus on her way home.Doctor – Okay, I understand your concern. Having a fever and cough doesn’t necessarily mean that someone has contracted the virus. These are symptoms of common cold too. The change in the temperature of the atmosphere could have triggered these symptoms. Still, to put your worries to rest, I am prescribing some medicines and an RT PCR test. Do the test by tomorrow, and if the test results are positive, make sure she is isolated. On the other hand, if the result is negative, just give her the medicine and ask her to drink a lot of water. Also, bring her in so I could examine her.Patient – Okay, doctor. I will bring her in the evening. Thank you.Doctor – You are welcome."},
    {text: "output: ```json\n{\n  \"summary\": \"Mr. Bose is concerned about his daughter who has been experiencing fever and a bad cough since returning from Pune, where her college was closed due to COVID-19. The doctor reassures Mr. Bose that these symptoms could be due to a common cold and advises him to have his daughter tested for COVID-19 using an RT-PCR test.  He prescribes medications and instructs Mr. Bose to isolate his daughter if the test comes back positive. If negative, he advises giving her the prescribed medication and plenty of fluids. The doctor also requests that Mr. Bose bring his daughter to the clinic for an examination later that evening.\",\n  \"medicines\": [\n    {\n      \"name\": \"N/A\",\n      \"dosage\": \"N/A\",\n      \"usage_instructions\": \"N/A\",\n      \"purpose\": \"To treat the symptoms, potentially common cold\"\n    }\n  ]\n}\n```"},
    {text: "input: Patient – Good Morning, doctor. May I come in?Doctor – Good Morning. How are you? You do look quite pale this morning.Patient – Yes, doctor. I’ve not been feeling well for the past few days. I’ve been having a stomach ache for a few days and feeling a bit dizzy since yesterday.Doctor – Okay, let me check. (applies pressure on the stomach and checks for pain) Does it hurt here?Patient – Yes, doctor, the pain there is the sharpest.Doctor – Well, you are suffering from a stomach infection, that’s the reason you are having a stomach ache and also getting dizzy. Did you change your diet recently or have something unhealthy?Patient – Actually, I went to a fair last week and ate food from the stalls there.Doctor – Okay, so you are probably suffering from food poisoning. Since the food stalls in fairs are quite unhygienic, there’s a high chance those uncovered food might have caused food poisoning.Patient – I think I will never eat from any unhygienic place in the future.Doctor – That’s good. I’m prescribing some medicines, have them for one week and come back for a checkup next week. And please try to avoid spicy and fried foods for now.Patient – Okay, doctor, thank you.Doctor – Welcome."},
    {text: "output: ```json\n{\n  \"summary\": \"The patient visits the doctor complaining of a stomach ache and dizziness for the past few days. The doctor, after examination, diagnoses the patient with a stomach infection, likely food poisoning due to consuming food from unhygienic food stalls at a fair. The doctor prescribes medication for a week and advises the patient to avoid spicy and fried foods for now. The patient agrees to follow the doctor's instructions and schedules a checkup for the following week.\",\n  \"medicines\": [\n    {\n      \"name\": \"N/A\",\n      \"dosage\": \"N/A\",\n      \"usage_instructions\": \"Take for one week.\",\n      \"purpose\": \"Treatment for stomach infection\"\n    }\n  ]\n}\n```"},
      { text: `input: ${transcription}` },  // Format transcription as input
      { text: 'output: {}' }  // Placeholder output
    ];

    const result = await model.generateContent({
      contents: [{ role: 'user', parts }],
      generationConfig,
    });

    const responseText = result.response.text();
    const responseData = JSON.parse(responseText);  // Parse the response

    // Check if responseData contains valid summary and medicines
    const summary = responseData.summary || 'Summary not available';
    const medicines = responseData.medicines || [];  // Default to empty array if undefined

    return { summary, medicines };
  } catch (error) {
    console.error('Error during Gemini AI summarization:', error);
    throw error;
  }
}

module.exports = {
  summarizeAndExtractPrescription,
};
